"use client";
import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { useMemo, useState, type FormEvent } from "react";
import { ArrowLeft, ArrowRight, BriefcaseBusiness, CalendarDays, Check, ChevronDown, ChevronLeft, CircleAlert, Filter, Laptop, MoreHorizontal, Pencil, Plus, Search, UserRound, Users, X } from "lucide-react";
import { useStore } from "@/lib/store";
import type { Employee } from "@/lib/types";
import { documentStatus, documentStatusLabel } from "@/lib/document-status";
import { isCurrentlyEmployedStatus } from "@/lib/hr-options";
import { isRegularizationDue, selectableMasterValues, matchesSearch } from "@/lib/hr-rules";

const blankEmployee: Omit<Employee, "id" | "createdAt" | "updatedAt"> = {
  employeeNumber: "", firstName: "", middleName: "", lastName: "", preferredName: "", email: "", phone: "", birthday: "",
  hiredAt: "", status: "", type: "", department: "", position: "", manager: "", supervisorId: "", client: "", clientAssignmentStartDate: "",
  location: "", regularizationDate: "", seat: "", device: "",
};
const fullName = (e: Employee) => [e.firstName, e.middleName, e.lastName].filter(Boolean).join(" ");
function Status({ value }: { value: string }) { return <span className={"status-pill " + (value === "Active" || value === "Regular" ? "good" : value === "Separated" ? "neutral" : "pending")}><i/>{value}</span>; }
function PageTitle({ title, description, action }: { title: string; description: string; action?: React.ReactNode }) { return <div className="page-title-row"><div><h1>{title}</h1><p className="muted">{description}</p></div>{action}</div>; }

export function EmployeesPage() {
  const { employees, archiveEmployee, references } = useStore();
  const params = useSearchParams();
  const [search, setSearch] = useState(params.get("search") ?? "");
  const [status, setStatus] = useState(params.get("status") ?? "All statuses");
  const [department, setDepartment] = useState("All departments");
  const [type, setType] = useState("All types");
  const [client, setClient] = useState("All clients");
  const [position, setPosition] = useState("All positions");
  const [location, setLocation] = useState("All locations");
  const [sort, setSort] = useState<"name" | "hired">("name");
  const [menu, setMenu] = useState("");
  const [filtersOpen, setFiltersOpen] = useState(false);
  const [page, setPage] = useState(1);
  const [confirm, setConfirm] = useState<Employee | null>(null);
  const rowsPerPage = 10;
  const today = new Date();
  const dueThrough = new Date(today.getFullYear(), today.getMonth(), today.getDate() + 30).toISOString().slice(0, 10);
  const dueOnly = params.get("filter") === "regularization-due";
  const withoutWorkstation = params.get("filter") === "without-workstation";
  const filtered = useMemo(() => employees.filter((e) => {
    if (e.archived) return false;
    return matchesSearch(search, [e.firstName, e.middleName, e.lastName, e.employeeNumber, e.position, e.email, e.department, e.client, e.location]) &&
      (!dueOnly || isRegularizationDue(e.status, e.regularizationDate, dueThrough)) &&
      (!withoutWorkstation || (isCurrentlyEmployedStatus(e.status, references.employmentStatuses) && !e.seat)) &&
      (status === "All statuses" || e.status === status) && (department === "All departments" || e.department === department) &&
      (type === "All types" || e.type === type) && (client === "All clients" || e.client === client) && (position === "All positions" || e.position === position) && (location === "All locations" || e.location === location);
  }).sort((a, b) => sort === "name" ? fullName(a).localeCompare(fullName(b)) : b.hiredAt.localeCompare(a.hiredAt)), [employees, references.employmentStatuses, search, status, department, type, client, position, location, sort, dueOnly, dueThrough, withoutWorkstation]);
  const pages = Math.max(1, Math.ceil(filtered.length / rowsPerPage));
  const rows = filtered.slice((page - 1) * rowsPerPage, page * rowsPerPage);
  return <div className="page-stack">
    <PageTitle title="Employees" description={dueOnly ? "Probationary employees due or overdue for review within 30 days." : withoutWorkstation ? "Currently employed employees without assigned resources." : "Manage employee records, assignments and employment status."} action={<Link className="button primary" href="/employees/new"><Plus size={16}/> Add employee</Link>} />
    <div className="directory-stats"><span><b>{employees.filter((e) => !e.archived).length}</b> employees</span><span><b>{employees.filter((e) => !e.archived && isCurrentlyEmployedStatus(e.status, references.employmentStatuses)).length}</b> employed</span><span><b>{employees.filter((e) => !e.archived && e.status === "Probationary").length}</b> probationary</span></div>
    <section className="directory-panel"><div className="directory-toolbar"><label className="search-box"><Search size={17}/><input aria-label="Search employees" placeholder="Search employees…" value={search} onChange={(e) => { setSearch(e.target.value); setPage(1); }}/>{search && <button aria-label="Clear search" className="plain-icon" onClick={() => setSearch("")}><X size={15}/></button>}</label><div className="directory-controls"><div className="filter-popover-wrap"><button className={"button secondary filter-trigger" + (filtersOpen ? " selected" : "")} aria-expanded={filtersOpen} onClick={() => setFiltersOpen(!filtersOpen)}><Filter size={15}/> Filters <span className="filter-count">{[status !== "All statuses", department !== "All departments", type !== "All types", client !== "All clients", position !== "All positions", location !== "All locations"].filter(Boolean).length || ""}</span></button>{filtersOpen && <div className="filter-popover"><label className="field"><span>Status</span><select value={status} onChange={(e) => {setStatus(e.target.value);setPage(1);}}><option>All statuses</option>{references.employmentStatuses.map((v)=><option key={v.id}>{v.name}</option>)}</select></label><label className="field"><span>Department</span><select value={department} onChange={(e) => {setDepartment(e.target.value);setPage(1);}}><option>All departments</option>{references.departments.map((v)=><option key={v.id}>{v.name}</option>)}</select></label><label className="field"><span>Employment type</span><select value={type} onChange={(e) => {setType(e.target.value);setPage(1);}}><option>All types</option>{references.employmentTypes.map((v)=><option key={v.id}>{v.name}</option>)}</select></label><label className="field"><span>Position</span><select value={position} onChange={(e) => {setPosition(e.target.value);setPage(1);}}><option>All positions</option>{references.positions.map((v)=><option key={v.id}>{v.name}</option>)}</select></label><label className="field"><span>Client</span><select value={client} onChange={(e) => {setClient(e.target.value);setPage(1);}}><option>All clients</option>{references.clients.map((v)=><option key={v.id}>{v.name}</option>)}</select></label><label className="field"><span>Location</span><select value={location} onChange={(e) => {setLocation(e.target.value);setPage(1);}}><option>All locations</option>{references.locations.map((v)=><option key={v.id}>{v.name}</option>)}</select></label></div>}</div><label className="sort-control"><span>Sort</span><select aria-label="Sort employees" value={sort} onChange={(e) => setSort(e.target.value as "name" | "hired")}><option value="name">Name</option><option value="hired">Date hired</option></select></label></div></div>
      {(status !== "All statuses" || department !== "All departments" || type !== "All types" || client !== "All clients" || position !== "All positions" || location !== "All locations") && <div className="active-filters">{[{value:status,reset:"All statuses",clear:setStatus},{value:department,reset:"All departments",clear:setDepartment},{value:type,reset:"All types",clear:setType},{value:client,reset:"All clients",clear:setClient},{value:position,reset:"All positions",clear:setPosition},{value:location,reset:"All locations",clear:setLocation}].filter((filter)=>filter.value!==filter.reset).map((filter)=><button key={filter.value} onClick={()=>{filter.clear(filter.reset);setPage(1);}}>{filter.value} <X size={13}/></button>)}<button className="clear-filters" onClick={()=>{setStatus("All statuses");setDepartment("All departments");setType("All types");setClient("All clients");setPosition("All positions");setLocation("All locations");}}>Clear all</button></div>}
      <div className="table-wrap employee-table-wrap"><table className="data-table employee-table"><thead><tr><th>Employee</th><th>Role</th><th>Department</th><th>Client</th><th>Status</th><th>Date hired</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{rows.map((e, i)=><tr key={e.id}><td><Link href={"/employees/" + e.id} className="employee-cell"><span className={"employee-avatar av-" + (i % 5)}>{e.firstName[0]}{e.lastName[0]}</span><span><b>{fullName(e)}</b><small>{e.employeeNumber}</small></span></Link></td><td><span className="table-primary">{e.position}</span></td><td><span className="table-secondary">{e.department}</span></td><td><span className="table-secondary">{e.client}</span></td><td><Status value={e.status}/></td><td><span className="table-secondary">{new Date(e.hiredAt + "T12:00:00").toLocaleDateString("en-PH",{month:"short",day:"numeric",year:"numeric"})}</span></td><td className="action-cell"><button className="icon-button tiny" aria-label={"Actions for " + fullName(e)} onClick={() => setMenu(menu === e.id ? "" : e.id)}><MoreHorizontal size={17}/></button>{menu === e.id && <div className="row-menu"><Link href={"/employees/" + e.id}>View profile</Link><Link href={"/employees/" + e.id + "/edit"}>Edit details</Link><button onClick={() => { setConfirm(e); setMenu(""); }}>Archive employee</button></div>}</td></tr>)}</tbody></table><div className="employee-mobile-list">{rows.map((e,i)=><div className="employee-mobile-row" key={e.id}><Link href={"/employees/"+e.id} className="employee-cell"><span className={"employee-avatar av-"+(i%5)}>{e.firstName[0]}{e.lastName[0]}</span><span><b>{fullName(e)}</b><small>{e.employeeNumber}</small></span></Link><span className="mobile-role">{e.position} · {e.department}</span><div><span className="table-secondary">{e.client}</span><Status value={e.status}/></div><Link aria-label={"Open "+fullName(e)} className="mobile-row-open" href={"/employees/"+e.id}><ArrowRight size={16}/></Link></div>)}</div>{rows.length === 0 && <div className="empty-state"><Users size={23}/><b>No employees match those filters</b><span>Try a different search or clear a filter.</span><button className="text-link" onClick={() => {setSearch("");setStatus("All statuses");setDepartment("All departments");setType("All types");setClient("All clients");setPosition("All positions");setLocation("All locations");}}>Clear filters</button></div>}</div>
      <div className="table-footer"><span>Showing <b>{filtered.length ? (page - 1) * rowsPerPage + 1 : 0}–{Math.min(page * rowsPerPage, filtered.length)}</b> of <b>{filtered.length}</b> employees</span><div className="pagination"><button aria-label="Previous page" disabled={page <= 1} onClick={() => setPage(page - 1)}><ChevronLeft size={16}/></button><span>Page {page} of {pages}</span><button aria-label="Next page" disabled={page >= pages} onClick={() => setPage(page + 1)}><ChevronDown className="rotate-270" size={16}/></button></div></div>
    </section>
    {confirm && <div className="modal-backdrop" role="presentation" onMouseDown={(e)=>{if(e.target===e.currentTarget)setConfirm(null);}}><section className="dialog" role="dialog" aria-modal="true" aria-labelledby="archive-title" onKeyDown={(e)=>{if(e.key==="Escape")setConfirm(null);}}><button className="icon-button dialog-close" aria-label="Close" onClick={()=>setConfirm(null)}><X size={18}/></button><span className="dialog-icon warning"><CircleAlert size={20}/></span><h2 id="archive-title">Archive employee?</h2><p>{fullName(confirm)} will be hidden from the active directory. Their employment history will remain available.</p><div className="dialog-actions"><button autoFocus className="button secondary" onClick={()=>setConfirm(null)}>Cancel</button><button className="button danger" onClick={()=>{archiveEmployee(confirm.id);setConfirm(null);}}>Archive employee</button></div></section></div>}
  </div>;
}

export function EmployeeFormPage({ id }: { id?: string }) {
  const { employees, resources, saveEmployee, references, error } = useStore();
  const router = useRouter();
  const existing = id ? employees.find((e) => e.id === id) : undefined;
  const existingSupervisor = existing?.supervisorId ? employees.find((employee) => employee.id === existing.supervisorId) : undefined;
  const [values, setValues] = useState<Omit<Employee, "id" | "createdAt" | "updatedAt">>(() => existing ? {
    employeeNumber: existing.employeeNumber, firstName: existing.firstName, middleName: existing.middleName, lastName: existing.lastName, preferredName: existing.preferredName, email: existing.email, phone: existing.phone, birthday: existing.birthday, hiredAt: existing.hiredAt, status: existing.status, type: existing.type, department: existing.department, position: existing.position, manager: existingSupervisor ? `${fullName(existingSupervisor)} · ${existingSupervisor.employeeNumber}` : existing.manager, supervisorId: existing.supervisorId ?? "", client: existing.client, clientAssignmentStartDate: existing.clientAssignmentStartDate, location: existing.location, regularizationDate: existing.regularizationDate, seat: existing.seat, device: existing.device,
  } : blankEmployee);
  const [errors, setErrors] = useState<Record<string, string>>({});
  const set = (field: keyof typeof values, value: string) => setValues((old) => ({
    ...old,
    [field]: value,
    ...(field === "manager" ? { supervisorId: employees.find((employee) => `${fullName(employee)} · ${employee.employeeNumber}` === value || fullName(employee) === value)?.id ?? "" } : {}),
    ...(field === "department" && old.department !== value ? { position: "" } : {}),
    ...(field === "client" && old.client !== value ? { clientAssignmentStartDate: value ? (existing ? new Date().toISOString().slice(0, 10) : old.hiredAt || new Date().toISOString().slice(0, 10)) : new Date().toISOString().slice(0, 10) } : {}),
  }));
  const field = (key: keyof typeof values, label: string, type = "text", required = false) => <label className="field"><span>{label}{required && <i> *</i>}</span><input type={type} value={String(values[key] ?? "")} onChange={(e)=>set(key,e.target.value)} aria-invalid={!!errors[key]} aria-describedby={errors[key] ? "err-" + key : undefined}/>{errors[key] && <small className="field-error" id={"err-" + key}>{errors[key]}</small>}</label>;
  const select = (key: keyof typeof values, label: string, options: string[], required = false, placeholder = `Select ${label.toLowerCase()}`, disabled = false) => <label className="field"><span>{label}{required && <i> *</i>}</span><select value={String(values[key] ?? "")} onChange={(e)=>set(key,e.target.value)} aria-invalid={!!errors[key]} aria-describedby={errors[key] ? "err-" + key : undefined} required={required} disabled={disabled}><option value="">{placeholder}</option>{options.map((option)=><option key={option} value={option}>{option}</option>)}</select>{errors[key] && <small className="field-error" id={"err-" + key}>{errors[key]}</small>}</label>;
  const current = existing;
  const departments = selectableMasterValues(references.departments,current?.department);
  const positions = selectableMasterValues(references.positions,current?.position).filter((item)=>!item.department_id||item.department_id===references.departments.find((d)=>d.name===values.department)?.id);
  const employmentTypes = selectableMasterValues(references.employmentTypes,current?.type);
  const employmentStatuses = selectableMasterValues(references.employmentStatuses,current?.status);
  const clients = selectableMasterValues(references.clients,current?.client);
  const locations = selectableMasterValues(references.locations,current?.location);
  const supervisorOptions=employees.filter(employee=>employee.id!==id&&((!employee.archived&&isCurrentlyEmployedStatus(employee.status,references.employmentStatuses))||employee.id===existing?.supervisorId)).map(employee=>`${fullName(employee)} · ${employee.employeeNumber}`);
  const resourceOptions = resources.filter((resource)=>resource.status==="Available"||resource.assignedTo===id);
  const [resourceIds,setResourceIds]=useState<string[]|null>(null);
  const selectedResourceIds = resourceIds ?? resources.filter((resource)=>resource.assignedTo===id).map((resource)=>resource.id);
  const [saving, setSaving] = useState(false);
  async function submit(e: FormEvent) {
    e.preventDefault();
    const next: Record<string,string> = {};
    for (const key of ["employeeNumber","firstName","lastName","email","hiredAt","status","type","department","position"] as const) if (!values[key].trim()) next[key] = "This field is required.";
    if(values.status==="Separated"&&existing?.status!=="Separated")next.status="Record a separation through Employee Lifecycle so the separation type and history are retained.";
    const allowed:Partial<Record<keyof typeof values,string[]>>={status:employmentStatuses.map(item=>item.name),type:employmentTypes.map(item=>item.name),department:departments.map(item=>item.name),position:positions.map(item=>item.name),client:clients.map(item=>item.name),location:locations.map(item=>item.name),manager:supervisorOptions};
    for(const [key,options] of Object.entries(allowed) as [keyof typeof values,string[]][])if(String(values[key]??"")&&!options.includes(String(values[key])))next[key]="Choose a value from the available master data.";
    if (values.email && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(values.email)) next.email = "Enter a valid email address.";
    if (values.phone && !/^[+0-9() -]{7,20}$/.test(values.phone)) next.phone = "Enter a valid phone number.";
    if (employees.some((e) => e.employeeNumber.toLowerCase() === values.employeeNumber.toLowerCase() && e.id !== id)) next.employeeNumber = "This employee number is already in use.";
    setErrors(next);
    if (Object.keys(next).length) { document.querySelector(".field-error")?.scrollIntoView({ behavior: "smooth", block: "center" }); return; }
    setSaving(true);
    try {
      await saveEmployee({ ...values, id: existing?.id },selectedResourceIds);
      router.push(existing ? "/employees/" + existing.id : "/employees");
    } catch { /* The shared workspace error banner contains the database error. */ }
    finally { setSaving(false); }
  }
  if (id && !existing) return <div className="not-found"><h1>Employee record not found</h1><Link href="/employees">Return to directory</Link></div>;
  return <div className="page-stack form-page"><div className="back-row"><Link href={existing ? "/employees/" + id : "/employees"}><ArrowLeft size={16}/> {existing ? "Back to employee profile" : "Back to directory"}</Link><span>Employee record</span></div><PageTitle title={existing ? "Edit employee" : "Add employee"} description={existing ? "Update personnel and employment information." : "Create an employee record using configured organization and assignment data."}/>
    <form className="employee-form panel" onSubmit={submit} noValidate><div className="form-section"><div className="form-section-title"><span className="section-number">01</span><div><h2>Personal information</h2><p>Basic identity and contact details</p></div></div><div className="form-fields two">{field("firstName","First name","text",true)}{field("middleName","Middle name")}{field("lastName","Last name","text",true)}{field("preferredName","Preferred name")}{field("birthday","Birthday","date")}{field("email","Email address","email",true)}{field("phone","Contact number","tel")}</div></div>
      <div className="form-section"><div className="form-section-title"><span className="section-number">02</span><div><h2>Employment</h2><p>Role, reporting line and employment dates</p></div></div><div className="form-fields two">{field("employeeNumber","Employee number","text",true)}{field("hiredAt","Date hired","date",true)}{select("status","Employee status",employmentStatuses.map((v)=>v.name),true)}{select("type","Employment type",employmentTypes.map((v)=>v.name),true)}{select("department","Department",departments.map((v)=>v.name),true)}{select("position","Position",positions.map((v)=>v.name),true,values.department ? "Select position" : "Select a department first",!values.department)}{select("manager","Supervisor / manager",supervisorOptions)}{field("regularizationDate","Expected regularization date","date")}</div></div>
      <div className="form-section"><div className="form-section-title"><span className="section-number">03</span><div><h2>Organization and assignment</h2><p>Client and work location are optional until assigned</p></div></div><div className="form-fields two">{select("client","Current client",clients.map((v)=>v.name))}{select("location","Work location",locations.map((v)=>v.name))}{values.client&&field("clientAssignmentStartDate","Client assignment start date","date")}</div><label className="field resource-assignment-field"><span>Resources <small>Optional · assign later if none are available</small></span><select multiple size={Math.min(5,Math.max(2,resourceOptions.length))} value={selectedResourceIds} onChange={(event)=>setResourceIds(Array.from(event.target.selectedOptions,option=>option.value))}>{resourceOptions.map(resource=><option key={resource.id} value={resource.id}>{resource.code} · {resource.type}{resource.assignedTo===id?" · currently assigned":" · available"}</option>)}</select>{!resourceOptions.length&&<small className="small-muted">No available resources. You can assign equipment later.</small>}</label></div>
      {error&&<p className="field-error" role="alert">{error}</p>}<div className="form-actions"><span><i>*</i> Required fields</span><div><Link className="button secondary" href={existing ? "/employees/" + id : "/employees"}>Cancel</Link><button className="button primary" type="submit" disabled={saving}><Check size={16}/>{saving?"Saving…":existing ? "Save changes" : "Create employee"}</button></div></div>
    </form>
  </div>;
}

export function EmployeeProfilePage({ id }: { id: string }) {
  const { employees, events, resources, archiveEmployee, audit } = useStore();
  const [tab,setTab] = useState(() => typeof window !== "undefined" && new URLSearchParams(window.location.search).get("tab") === "201-files" ? "201 files" : "Overview");
  const employee = employees.find((e)=>e.id===id);
  if (!employee) return <div className="not-found"><h1>Employee record not found</h1><p>This record may not be visible to your account.</p><Link href="/employees">Return to directory</Link></div>;
  const name = [employee.firstName,employee.middleName,employee.lastName].filter(Boolean).join(" ");
  const history = events.filter((e)=>e.employeeId===id).sort((a,b)=>b.effectiveDate.localeCompare(a.effectiveDate));
  const assigned = resources.filter((r)=>r.assignedTo===id);
  const lifecycleLogIds = new Set(audit.filter((entry)=>entry.entity_type==="employee_lifecycle_events").map((entry)=>entry.entity_id));
  const lifecycleTimes = history.map((event)=>new Date(event.recordedAt).getTime());
  const activityAudit = audit.filter((entry)=>{
    const payloads=[entry.old_data,entry.new_data].filter((value)=>value&&typeof value==="object"&&!Array.isArray(value)) as Record<string,unknown>[];
    const related=entry.entity_id===id || payloads.some((payload)=>payload.employee_id===id);
    if(!related || entry.entity_type==="employee_lifecycle_events" || entry.entity_type==="employee_client_assignments" || entry.entity_type==="resources") return false;
    if(lifecycleLogIds.has(entry.entity_id)) return false;
    if(entry.entity_type==="employees"&&lifecycleTimes.some((time)=>Math.abs(time-new Date(entry.created_at).getTime())<2000)) return false;
    return true;
  });
  const activityItems=[
    ...history.map((event)=>({id:`lifecycle-${event.id}`,kind:"Lifecycle event",title:event.type,detail:[event.separationType,event.previousValue&&event.newValue?[event.previousValue,event.newValue].join(" → "):event.newValue||event.notes].filter(Boolean).join(" · "),date:event.recordedAt,actor:event.recordedBy})),
    ...activityAudit.map((entry)=>({id:`audit-${entry.id}`,kind:"System audit",title:entry.action.replaceAll("."," "),detail:"System-recorded change",date:entry.created_at,actor:entry.actor_name})),
  ].sort((a,b)=>b.date.localeCompare(a.date));
  return <div className="page-stack profile-page"><div className="back-row"><Link href="/employees"><ArrowLeft size={16}/> Employees</Link><span>EMPLOYEE · {employee.employeeNumber}</span></div>{employee.archived&&<div className="inline-error" role="status">This employee is archived. Their record and history are retained.</div>}<section className="profile-header"><span className="profile-avatar">{employee.firstName[0]}{employee.lastName[0]}</span><div className="profile-heading"><p className="section-overline">EMPLOYEE RECORD</p><h1>{name}</h1><p>{employee.position} <span>·</span> {employee.department}</p><div className="profile-meta"><Status value={employee.status}/><span>{employee.employeeNumber}</span></div></div><div className="profile-actions">{!employee.archived&&<><Link className="button secondary" href={"/employees/" + id + "/edit"}><Pencil size={15}/> Edit employee</Link><button className="icon-button profile-more" title="Archive employee" onClick={()=>{if(window.confirm("Archive " + name + "? Their history will remain available."))void archiveEmployee(id);}}><MoreHorizontal size={18}/></button></>}</div></section><section className="profile-assignment"><span className="profile-assignment-label">{employee.archived?"OPEN ASSIGNMENT · ARCHIVED RECORD":"CURRENT ASSIGNMENT"}</span><b>{employee.client || "Unassigned"}</b><span>{employee.type} employee <i/> {employee.location}</span><ArrowRight size={16}/></section>
    <div className="profile-tabs" role="tablist" aria-label="Employee record sections">{["Overview","Employment history","201 files","Resources","Activity"].map((t)=><button role="tab" aria-selected={tab===t} className={tab===t?"active":""} key={t} onClick={()=>setTab(t)}>{t}</button>)}</div>
    {tab==="Overview" && <div className="profile-content-grid"><section className="panel profile-section"><div className="panel-head"><div><h2>Personal information</h2><p>Employee identity and contact details</p></div><UserRound size={17}/></div><div className="detail-grid"><div><small>Full name</small><b>{name}</b></div><div><small>Preferred name</small><b>{employee.preferredName || "—"}</b></div><div><small>Date of birth</small><b>{employee.birthday ? new Date(employee.birthday+"T12:00:00").toLocaleDateString("en-PH",{month:"long",day:"numeric",year:"numeric"}) : "—"}</b></div><div><small>Email address</small><b>{employee.email}</b></div><div><small>Contact number</small><b>{employee.phone || "—"}</b></div></div></section><section className="panel profile-section"><div className="panel-head"><div><h2>Employment details</h2><p>Current appointment and branch assignment</p></div><BriefcaseBusiness size={17}/></div><div className="detail-grid"><div><small>Department</small><b>{employee.department}</b></div><div><small>Position</small><b>{employee.position}</b></div><div><small>Employment type</small><b>{employee.type}</b></div><div><small>Date hired</small><b>{new Date(employee.hiredAt+"T12:00:00").toLocaleDateString("en-PH",{month:"long",day:"numeric",year:"numeric"})}</b></div><div><small>Supervisor / manager</small><b>{employee.manager || "—"}</b></div><div><small>Client assignment</small><b>{employee.client}</b></div><div><small>Regularization date</small><b>{employee.regularizationDate ? new Date(employee.regularizationDate+"T12:00:00").toLocaleDateString("en-PH",{month:"long",day:"numeric",year:"numeric"}) : "—"}</b></div><div><small>Work location</small><b>{employee.location}</b></div></div></section><section className="panel profile-section"><div className="panel-head"><div><h2>Assigned resources</h2><p>Seat and equipment linked to this employee</p></div><Laptop size={17}/></div>{assigned.length ? <div className="resource-compact">{assigned.map((r)=><div key={r.id}><span>{r.type}</span><b>{r.code}</b><small>{r.location}</small></div>)}</div> : <div className="inline-empty">No resources assigned yet. <Link href="/resources">Manage resources</Link></div>}</section></div>}
    {tab==="Employment history" && <section className="panel profile-section"><div className="panel-head"><div><h2>Employment history</h2><p>Recorded lifecycle events and role changes</p></div><Link className="button secondary small-button" href="/workforce/lifecycle">Record event</Link></div><EventTimeline events={history} employeeName={name}/></section>}
    {tab==="201 files" && <section className="panel profile-section"><div className="panel-head"><div><h2>201 file checklist</h2><p>Document completeness for this employee</p></div><Link className="button secondary small-button" href="/records/201-files">Manage documents</Link></div><DocumentChecklist employeeId={id}/></section>}
    {tab==="Resources" && <section className="panel profile-section"><div className="panel-head"><div><h2>Assigned resources</h2><p>Tracked seat and equipment assignments</p></div><Link className="text-link" href="/resources">Manage resources <ArrowRight size={14}/></Link></div>{assigned.length ? <div className="resource-table">{assigned.map((r)=><div key={r.id}><Laptop size={17}/><span><b>{r.code}</b><small>{r.type}</small></span><span>{r.location}</span><Status value={r.status}/></div>)}</div> : <div className="inline-empty">No resources currently assigned.</div>}</section>}
    {tab==="Activity" && <section className="panel profile-section"><div className="panel-head"><div><h2>Activity history</h2><p>Lifecycle events and system-recorded changes</p></div></div>{activityItems.length?<div className="timeline">{activityItems.map(item=><div className="timeline-row" key={item.id}><span className="timeline-marker"/><div><div className="timeline-heading"><b>{item.title}</b><time>{new Date(item.date).toLocaleDateString("en-PH",{month:"short",day:"numeric",year:"numeric"})}</time></div><span className="event-tag">{item.kind}</span>{item.detail&&<p>{item.detail}</p>}<small>{item.actor} · {new Date(item.date).toLocaleTimeString("en-PH",{hour:"numeric",minute:"2-digit"})}</small></div></div>)}</div>:<EventTimeline events={history} employeeName={name}/>}</section>}
  </div>;
}

export function EventTimeline({events,employeeName}:{events:{id:string;type:string;effectiveDate:string;previousValue:string;newValue:string;notes:string;recordedAt:string;recordedBy?:string;separationType?:string}[];employeeName:string}) {
  if(!events.length)return <div className="empty-state compact"><CalendarDays size={22}/><b>No events recorded yet</b><span>Lifecycle updates for {employeeName} will appear here.</span></div>;
  return <div className="timeline">{events.map((event)=><div className="timeline-row" key={event.id}><span className="timeline-marker"/><div><div className="timeline-heading"><b>{event.type}</b><time>{new Date(event.effectiveDate+"T12:00:00").toLocaleDateString("en-PH",{month:"short",day:"numeric",year:"numeric"})}</time></div><p>{event.previousValue && <>{event.previousValue} <ArrowRight size={13}/> </>}{event.newValue}</p>{event.separationType&&<small>Separation type · {event.separationType}</small>}{event.notes && <small>{event.notes}</small>}<small className="timeline-recorded">Recorded by {event.recordedBy || "HR team"} · {new Date(event.recordedAt).toLocaleTimeString("en-PH",{hour:"numeric",minute:"2-digit"})}</small></div></div>)}</div>;
}
export function DocumentChecklist({employeeId}:{employeeId:string}) {
  const {documents,documentExemptions,references,openDocument}=useStore();
  const required=references.documentTypes.filter(type=>type.is_active&&type.is_required);
  return <div className="document-list">{required.map(type=>{const doc=documents.find(item=>item.employee_id===employeeId&&item.document_type_id===type.id);const exemption=documentExemptions.find(item=>item.employee_id===employeeId&&item.document_type_id===type.id);const status=documentStatusLabel(documentStatus({document:doc,required:true,notApplicable:!!exemption}));return <div key={type.id}><span className={"document-status "+(status==="Complete"||status==="Not Applicable"?"doc-done":status==="Expiring Soon"?"doc-expiring":"doc-missing")}>{status==="Complete"||status==="Not Applicable"?<Check size={13}/>:<CircleAlert size={13}/>}</span><span><b>{type.name}</b><small>{exemption?`Not applicable · ${exemption.reason}`:doc?.original_filename??"Required document missing"}</small></span><span className="document-label">{status}</span>{doc&&<button className="plain-icon" title="Open secure document" onClick={async()=>{try{window.open(await openDocument(doc.file_path),"_blank","noopener,noreferrer");}catch{}}}><Laptop size={14}/></button>}</div>;})}</div>;
}
