import ExcelJS from "exceljs";
import PDFDocument from "pdfkit";
import type { MonthlyReport } from "@/lib/monthly-report";

const monthName = (month: number, year: number) => new Intl.DateTimeFormat("en-PH", { month: "long", year: "numeric", timeZone: "Asia/Manila" }).format(new Date(Date.UTC(year, month - 1, 1, 12)));

const eventRows = (rows: MonthlyReport["movements"]["all"]) => rows.map((r) => ({ "Employee ID": r.employeeNumber, Employee: r.employee, Movement: r.type, "Effective date": r.effectiveDate, Previous: r.previous, New: r.next, Department: r.department, Position: r.position }));

export async function createMonthlyWorkbook(report: MonthlyReport): Promise<Buffer> {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = report.metadata.generatedBy;
  workbook.subject = "Monthly Human Resources Report";
  workbook.title = `Monthly HR Report - ${report.metadata.label}`;
  workbook.created = new Date();
  const add = (name: string, title: string, rows: Record<string, string | number | null | undefined>[]) => {
    const sheet = workbook.addWorksheet(name);
    sheet.addRow(["RRF HR Nexus"]);
    sheet.addRow(["Monthly Human Resources Report"]);
    sheet.addRow([`${report.metadata.branch} · ${report.metadata.label}`]);
    sheet.addRow([`Generated: ${report.metadata.generatedAt} · Generated by: ${report.metadata.generatedBy}`]);
    sheet.addRow([]);
    sheet.addRow([title]);
    if (rows.length) {
      const headers = Object.keys(rows[0]);
      sheet.addRow(headers);
      for (const row of rows) sheet.addRow(headers.map((header) => row[header] ?? ""));
      const headerRow = 7;
      sheet.getRow(headerRow).font = { bold: true, color: { argb: "FFFFFFFF" } };
      sheet.getRow(headerRow).fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF9F1D2A" } };
      sheet.views = [{ state: "frozen", ySplit: headerRow }];
      for (let col = 1; col <= headers.length; col++) {
        const values = sheet.getColumn(col).values.map((value) => String(value ?? ""));
        const width = Math.max(12, Math.min(34, ...values.map((value) => value.length + 2)));
        sheet.getColumn(col).width = width;
      }
      for (let rowNumber = headerRow + 1; rowNumber <= sheet.rowCount; rowNumber++) {
        const row = sheet.getRow(rowNumber);
        row.eachCell((cell, colNumber) => {
          if (cell.value && typeof cell.value === "string" && /^\d{4}-\d{2}-\d{2}$/.test(cell.value)) { cell.value = new Date(`${cell.value}T12:00:00.000Z`); cell.numFmt = "dd mmm yyyy"; }
          if (headers[colNumber - 1]?.includes("%") && typeof cell.value === "number") cell.numFmt = "0%";
        });
      }
    } else {
      sheet.addRow(["No records for this period."]);
    }
    sheet.getRow(1).font = { bold: true, size: 16, color: { argb: "FF9F1D2A" } };
    sheet.getRow(2).font = { bold: true, size: 13 };
    sheet.getRow(6).font = { bold: true, size: 12 };
    sheet.views = [{ state: "frozen", ySplit: rows.length ? 7 : 6 }];
    return sheet;
  };
  add("Monthly Summary", "Workforce and operations summary", [
    { Metric: "Workforce at period end", Value: report.workforce.total },
    { Metric: "Active employees", Value: report.workforce.active }, { Metric: "Probationary", Value: report.workforce.probationary },
    { Metric: "Regular", Value: report.workforce.regular }, { Metric: "On leave", Value: report.workforce.onLeave },
    { Metric: "Separated", Value: report.workforce.separated }, { Metric: "New hires during month", Value: report.workforce.hires },
    { Metric: "Separations during month", Value: report.workforce.separations }, { Metric: "201 completion", Value: `${report.compliance.completion}%` },
    { Metric: "Employees requiring 201 files", Value: report.compliance.required }, { Metric: "Fully compliant", Value: report.compliance.compliant },
    { Metric: "Employees with missing documents", Value: report.compliance.withMissing }, { Metric: "Employees with expiring documents", Value: report.compliance.withExpiring },
    { Metric: "Employees with expired documents", Value: report.compliance.withExpired }, { Metric: "Total resources", Value: report.resources.total },
    { Metric: "Assigned / Available / Maintenance", Value: `${report.resources.assigned} / ${report.resources.available} / ${report.resources.maintenance}` },
    { Metric: "Workstations: total / occupied / available", Value: `${report.resources.workstationTotal} / ${report.resources.workstationOccupied} / ${report.resources.workstationAvailable}` },
    { Metric: "New hires / regularizations / promotions", Value: `${report.movements.hires.length} / ${report.movements.regularizations.length} / ${report.movements.promotions.length}` },
    { Metric: "Transfers / client changes / separations", Value: `${report.movements.transfers.length} / ${report.assignments.length} / ${report.movements.separations.length}` },
    { Metric: "Comparison note", Value: report.comparison.note },
  ]);
  add("Workforce Snapshot", "Employees at reporting period end", report.workforce.employees.map((e) => ({ "Employee ID": e.number, Employee: e.name, Department: e.department, Position: e.position, "Employment type": e.employmentType, Status: e.status, Client: e.client, Location: e.location, "Date hired": e.hireDate })));
  add("New Hires", "New hires during the month", report.movements.hires.map((e) => ({ "Employee ID": e.employeeNumber, Employee: e.employee, Position: e.position, Department: e.department, "Effective date": e.effectiveDate })));
  add("Lifecycle Movements", "Recorded employee movements", eventRows([...report.movements.regularizations, ...report.movements.promotions, ...report.movements.transfers, ...report.movements.separations]));
  add("Client Assignments", "Client reassignments during the month", report.assignments.map((e) => ({ "Employee ID": e.employeeNumber, Employee: e.employee, "Previous client": e.previousClient, "New client": e.newClient, "Effective date": e.effectiveDate })));
  add("201 File Compliance", "Employees requiring attention", report.compliance.rows.map((e) => ({ "Employee ID": e.employeeNumber, Employee: e.employee, "Completion %": e.completion / 100, "Missing documents": e.missing.join("; "), "Expiring documents": e.expiring.join("; "), "Expired documents": e.expired.join("; "), Status: e.status })));
  add("Resource Summary", "Inventory and resource movements", [
    { Resource: "Total resources", Type: "", Employee: "", Action: report.resources.total, "Effective date": "" },
    { Resource: "Assigned", Type: "", Employee: "", Action: report.resources.assigned, "Effective date": "" },
    { Resource: "Available", Type: "", Employee: "", Action: report.resources.available, "Effective date": "" },
    { Resource: "Maintenance", Type: "", Employee: "", Action: report.resources.maintenance, "Effective date": "" },
    ...report.resources.movements.map((e) => ({ Resource: e.resource, Type: e.type, Employee: e.employee, Action: e.action, "Effective date": e.date })),
  ]);
  add("People Events", "Birthdays and work anniversaries", [
    ...report.birthdays.map((e) => ({ Category: "Birthday", Employee: e.employee, Department: e.department, Date: e.date, "Years of service": "" })),
    ...report.anniversaries.map((e) => ({ Category: "Work anniversary", Employee: e.employee, Department: e.department, Date: e.hireDate, "Years of service": e.years })),
  ]);
  const result = await workbook.xlsx.writeBuffer();
  return Buffer.from(result);
}

export async function createMonthlyPdf(report: MonthlyReport): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: "A4", margin: 44, bufferPages: true, info: { Title: `Monthly HR Report - ${report.metadata.label}`, Author: report.metadata.generatedBy } });
      const chunks: Buffer[] = [];
      doc.on("data", (chunk: Buffer) => chunks.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(chunks)));
      doc.on("error", reject);
      const red = "#9F1D2A"; const charcoal = "#252525"; const muted = "#666666";
      const pageWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;
      const drawHeader = () => {
        doc.fillColor(red).font("Helvetica-Bold").fontSize(17).text("RRF HR Nexus");
        doc.fillColor(charcoal).fontSize(13).text("Monthly Human Resources Report");
        doc.fillColor(muted).font("Helvetica").fontSize(9).text(`${report.metadata.branch} · Reporting period: ${report.metadata.label}`);
        doc.text(`Generated: ${report.metadata.generatedAt} · Generated by: ${report.metadata.generatedBy}`);
        doc.moveDown(1.1);
      };
      const ensureRoom = (needed: number) => { if (doc.y + needed > doc.page.height - 55) { doc.addPage(); drawHeader(); } };
      const heading = (title: string) => { ensureRoom(34); doc.moveDown(0.5).fillColor(red).font("Helvetica-Bold").fontSize(12).text(title); doc.moveDown(0.3); };
      const line = (label: string, value: string | number) => { ensureRoom(17); doc.fillColor(charcoal).font("Helvetica-Bold").fontSize(9).text(`${label}: `, { continued: true }); doc.font("Helvetica").text(String(value)); };
      const table = (headers: string[], rows: string[][]) => {
        const widths = headers.map(() => pageWidth / headers.length);
        const drawRow = (cells: string[], header: boolean) => {
          const height = 21;
          if (doc.y + height > doc.page.height - 55) {
            doc.addPage(); drawHeader();
            if (!header) drawRow(headers, true);
          }
          const y = doc.y; let x = doc.page.margins.left;
          cells.forEach((cell, index) => {
            if (header) doc.rect(x, y, widths[index], height).fill(red);
            else doc.rect(x, y, widths[index], height).fill(index % 2 ? "#FFFFFF" : "#F7F5F3");
            doc.fillColor(header ? "#FFFFFF" : charcoal).font(header ? "Helvetica-Bold" : "Helvetica").fontSize(7.5).text(String(cell ?? ""), x + 4, y + 6, { width: widths[index] - 8, height: height - 4, ellipsis: true });
            x += widths[index];
          });
          doc.y = y + height;
        };
        drawRow(headers, true);
        if (!rows.length) drawRow(["No records for this period.", ...headers.slice(1).map(() => "")], false);
        else rows.forEach((row) => drawRow(row, false));
        doc.moveDown(0.35);
      };
      drawHeader();
      heading(`Workforce at ${report.metadata.periodEnd}`);
      line("Total employees", report.workforce.total); line("Active", report.workforce.active); line("Probationary", report.workforce.probationary); line("Regular", report.workforce.regular); line("On leave", report.workforce.onLeave); line("Separated", report.workforce.separated);
      heading(`Movement during ${report.metadata.label}`);
      line("New hires", report.movements.hires.length); line("Regularizations", report.movements.regularizations.length); line("Promotions / position changes", report.movements.promotions.length); line("Transfers", report.movements.transfers.length); line("Client reassignments", report.assignments.length); line("Separations", report.movements.separations.length);
      heading("Monthly workforce movement summary");
      table(["Movement", "Count"], [["New hires", String(report.movements.hires.length)], ["Regularizations", String(report.movements.regularizations.length)], ["Promotions", String(report.movements.promotions.length)], ["Department transfers", String(report.movements.departmentChanges.length)], ["Client reassignments", String(report.assignments.length)], ["Separations", String(report.movements.separations.length)]]);
      heading("201 File Compliance");
      line("Employees requiring 201 files", report.compliance.required); line("Fully compliant employees", report.compliance.compliant); line("Employees with missing documents", report.compliance.withMissing); line("Employees with expiring documents", report.compliance.withExpiring); line("Employees with expired documents", report.compliance.withExpired); line("Overall completion", `${report.compliance.completion}%`);
      table(["Employee", "Complete", "Missing", "Expiring", "Expired", "Status"], report.compliance.rows.map((e) => [e.employee, `${e.completion}%`, e.missing.length ? e.missing.join(", ") : "0", e.expiring.length ? e.expiring.join(", ") : "0", e.expired.length ? e.expired.join(", ") : "0", e.status]));
      heading("Document Expirations");
      line("Expired during reporting month", report.expirations.expired.length); table(["Employee", "Document", "Expiry date"], report.expirations.expired.map((e) => [e.employee, e.document, e.date]));
      heading(`Upcoming in ${monthName(report.metadata.month === 12 ? 1 : report.metadata.month + 1, report.metadata.month === 12 ? report.metadata.year + 1 : report.metadata.year)}`);
      table(["Employee", "Document", "Expiry date"], report.expirations.upcoming.map((e) => [e.employee, e.document, e.date]));
      heading("Resource / Workstation Summary");
      line("Resources: total / assigned / available / maintenance / inactive", `${report.resources.total} / ${report.resources.assigned} / ${report.resources.available} / ${report.resources.maintenance} / ${report.resources.inactive}`);
      line("Workstations: total / occupied / available", `${report.resources.workstationTotal} / ${report.resources.workstationOccupied} / ${report.resources.workstationAvailable}`);
      line("Assignments / releases / reassignments this month", `${report.resources.newAssignments} / ${report.resources.releases} / ${report.resources.reassignments}`);
      table(["Resource", "Type", "Employee", "Action", "Date"], report.resources.movements.map((e) => [e.resource, e.type, e.employee, e.action, e.date]));
      heading("Birthdays"); table(["Employee", "Department", "Birthday"], report.birthdays.map((e) => [e.employee, e.department, e.date]));
      heading("Work Anniversaries"); table(["Employee", "Department", "Hire date", "Years of service"], report.anniversaries.map((e) => [e.employee, e.department, e.hireDate, String(e.years)]));
      heading("Regularization Monitoring");
      line("Completed this month", report.regularizationMonitoring.completed.length);
      table(["Category", "Employee", "Department", "Hire date", "Expected date"], [
        ...report.regularizationMonitoring.dueNextMonth.map((e) => ["Due next month", e.employee, e.department, e.hireDate, e.expectedDate]),
        ...report.regularizationMonitoring.overdue.map((e) => ["Overdue", e.employee, e.department, e.hireDate, e.expectedDate]),
      ]);
      heading("Month-to-Month Change Summary");
      line("Comparison", `${report.comparison.previousLabel} vs ${report.comparison.currentLabel}`);
      table(["Metric", report.comparison.previousLabel, report.comparison.currentLabel, "Change"], report.comparison.metrics.map((e) => [e.label, `${e.previous}${e.suffix ?? ""}`, `${e.current}${e.suffix ?? ""}`, `${e.delta > 0 ? "+" : ""}${e.delta}${e.suffix ?? ""}`]));
      doc.fillColor(muted).font("Helvetica").fontSize(8).text(report.comparison.note, { width: pageWidth });
      heading("Employee Movements");
      table(["Employee", "Movement", "Effective", "Previous", "New"], [...report.movements.all, ...report.assignments.map((e, i) => ({ id: `ca-${i}`, employee: e.employee, type: "Client Reassignment", effectiveDate: e.effectiveDate, previous: e.previousClient, next: e.newClient }))].map((e) => [e.employee, e.type, e.effectiveDate, e.previous, e.next]));
      const range = doc.bufferedPageRange();
      for (let page = range.start; page < range.start + range.count; page++) {
        doc.switchToPage(page);
        const y = doc.page.height - 34;
        doc.save().strokeColor("#E2DEDA").moveTo(doc.page.margins.left, y - 9).lineTo(doc.page.width - doc.page.margins.right, y - 9).stroke();
        doc.fillColor(muted).font("Helvetica").fontSize(8).text(`RRF HR Nexus · Monthly HR Report — ${report.metadata.label}`, doc.page.margins.left, y, { width: pageWidth / 2, lineBreak: false });
        doc.text(`Page ${page + 1} of ${range.count}`, doc.page.margins.left + pageWidth / 2, y, { width: pageWidth / 2, align: "right", lineBreak: false });
        doc.restore();
      }
      doc.end();
    } catch (error) { reject(error); }
  });
}
